name: Build

on:
  push:
    branches: [ 'nightly']

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: 'containerd/stargz-snapshotter'

      - name: Build
        run: |
          export GOARCH=arm64
          export GOOS=linux
          make containerd-stargz-grpc
          make ctr-remote
          tar -cvf stargz-snapshotter-nightly-linux-arm64.tar ./out
          gzip stargz-snapshotter-nightly-linux-arm64.tar
          ls