name: Build

on:
  push:
    branches: [ 'nightly']

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main


      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: 'containerd/stargz-snapshotter'
          path: stargz-snapshotter

      - name: Build
        working-directory: ./stargz-snapshotter
        run: |
          export GOARCH=arm64
          export GOOS=linux
          make containerd-stargz-grpc
          make ctr-remote
          tar -cvf stargz-snapshotter-nightly-linux-arm64.tar ./out/
          gzip stargz-snapshotter-nightly-linux-arm64.tar
          mv stargz-snapshotter-nightly-linux-arm64.tar.gz ./../main/releases/

      - name: Update artifacts
        working-directory: ./main
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "nightly artifacts updated"
          git push
